# Generated by Django 4.1 on 2022-08-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pythno', 'Python'), ('java', 'Java'), ('rust', 'Rust'), ('c++', 'C++')], default='', max_length=6)),
                ('project_title', models.CharField(max_length=300)),
                ('source', models.CharField(max_length=300)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
